//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToeVNovikov.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToeVNovikov.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player Age must be beetwen {0} and {1} ages.
        /// </summary>
        internal static string AgeIsOutOfLimits {
            get {
                return ResourceManager.GetString("AgeIsOutOfLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player#{0} ({1}) is winner.
        /// </summary>
        internal static string AnnouncementOfWinner {
            get {
                return ResourceManager.GetString("AnnouncementOfWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input command: .
        /// </summary>
        internal static string AskForCommand {
            get {
                return ResourceManager.GetString("AskForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Would you like to start new TicTacToe game?{0}..Press Enter to begin or any othe button to exit.
        /// </summary>
        internal static string AskForNewGame {
            get {
                return ResourceManager.GetString("AskForNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player #{0} Input your Id Name Age if you registered, or Input your Name Age if you are not registered.
        /// </summary>
        internal static string AskForPlayerInfo {
            get {
                return ResourceManager.GetString("AskForPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player #{0} ({1}) input two numbers in range of [1-{2}]:.
        /// </summary>
        internal static string AskForPlayerTurn {
            get {
                return ResourceManager.GetString("AskForPlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The command was executed and a file with the name {0} was created.
        /// </summary>
        internal static string CommandExecuted {
            get {
                return ResourceManager.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cordinates out of range of gamefield, must be two numbers from 1 to {0}.
        /// </summary>
        internal static string CordinatesOutOfRange {
            get {
                return ResourceManager.GetString("CordinatesOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DRAW.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player name can&apos;t be empty or contain only whitespaces.
        /// </summary>
        internal static string EmptyPlayerName {
            get {
                return ResourceManager.GetString("EmptyPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на generate file-report in json format with ALL game results.
        /// </summary>
        internal static string GenerateAllResultsDescription {
            get {
                return ResourceManager.GetString("GenerateAllResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на generate file-report in json format with last game result.
        /// </summary>
        internal static string GenerateLastGameResultDescription {
            get {
                return ResourceManager.GetString("GenerateLastGameResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на show all games where two current players take part together.
        /// </summary>
        internal static string GenerateResultsForCurrentPlayersDescription {
            get {
                return ResourceManager.GetString("GenerateResultsForCurrentPlayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на show you all available command and theirs description.
        /// </summary>
        internal static string HelpDescription {
            get {
                return ResourceManager.GetString("HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id = {0} is alredy occupied by another Player.
        /// </summary>
        internal static string IdIsOccupied {
            get {
                return ResourceManager.GetString("IdIsOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid player info:.
        /// </summary>
        internal static string InvalidPlayerInfo {
            get {
                return ResourceManager.GetString("InvalidPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is for {1}.
        /// </summary>
        internal static string KeyIsForValue {
            get {
                return ResourceManager.GetString("KeyIsForValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Your age can&apos;t be lesser than before&quot;.
        /// </summary>
        internal static string LesserAge {
            get {
                return ResourceManager.GetString("LesserAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This spot is alredy marked, try another.
        /// </summary>
        internal static string MarkedSpot {
            get {
                return ResourceManager.GetString("MarkedSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write the necessary abbreviation to choose language.
        /// </summary>
        internal static string NecessaryAbbreviation {
            get {
                return ResourceManager.GetString("NecessaryAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abbreviation can&apos;t be null.
        /// </summary>
        internal static string NullAbbreviation {
            get {
                return ResourceManager.GetString("NullAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command can&apos;t be null.
        /// </summary>
        internal static string NullCommand {
            get {
                return ResourceManager.GetString("NullCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information about Player can&apos;t be null.
        /// </summary>
        internal static string NullPlayerInfo {
            get {
                return ResourceManager.GetString("NullPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player name can&apos;t be null.
        /// </summary>
        internal static string NullPlayerName {
            get {
                return ResourceManager.GetString("NullPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information about turn can&apos;t be null.
        /// </summary>
        internal static string NullPlayerTurnInfo {
            get {
                return ResourceManager.GetString("NullPlayerTurnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player name length must be beetwen {0} and {1} characters.
        /// </summary>
        internal static string PlayerNameLengthIsOutOfLimits {
            get {
                return ResourceManager.GetString("PlayerNameLengthIsOutOfLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you dont want to input commands anymore.
        /// </summary>
        internal static string SkipDescription {
            get {
                return ResourceManager.GetString("SkipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на you made {0} mistakes in a row, your turn is skipped.
        /// </summary>
        internal static string SkippedTurn {
            get {
                return ResourceManager.GetString("SkippedTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registation complited successfully, {0} your Id = {1} remember it!.
        /// </summary>
        internal static string SuccessfullRegistation {
            get {
                return ResourceManager.GetString("SuccessfullRegistation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The is no available localization with this abbriveation ({0}).
        /// </summary>
        internal static string UnknownAbbreviation {
            get {
                return ResourceManager.GetString("UnknownAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In a list of commands there is no one with name {0}. you can use command /help to see all available commands.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No similar was found among the registered players, check the correctness of the data entry or register by entering your Name Age.
        /// </summary>
        internal static string UnknownPlayer {
            get {
                return ResourceManager.GetString("UnknownPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong format of Info, must be Id Name Age if you are registered or Name Age if you aren&apos;t.
        /// </summary>
        internal static string WrongFormatOfPlayerInfo {
            get {
                return ResourceManager.GetString("WrongFormatOfPlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong format of Info,must be two numbers from 1 to {0}.
        /// </summary>
        internal static string WrongFormatOfTurnInfo {
            get {
                return ResourceManager.GetString("WrongFormatOfTurnInfo", resourceCulture);
            }
        }
    }
}
